/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicios.programacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class figuras extends javax.swing.JFrame {

    /**
     * Creates new form figuras
     */
    public figuras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Calculo de perímetro y área de figuras geométricas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione una opción>", "Triángulo", "Cuadrado", "Rectángulo", "Rombo", "Romboide", "Trapecio" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel2.setText("Base :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 70, -1));

        jLabel3.setText("Altura:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 70, -1));

        jLabel4.setText("Lado 1:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 70, -1));

        jLabel5.setText("Lado 2:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 70, -1));

        jLabel6.setText("Lado 3:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 70, -1));

        jLabel7.setText("Lado 4:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 70, -1));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Triángulo")){
            jLabel2.setText("Base");
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel3.setText("Altura");
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(false);
            jLabel4.setText("Lado 1");
            jLabel5.setText("Lado 2");
            jLabel6.setText("Lado 3");
            jTextField2.setVisible(true);
             jTextField3.setVisible(true);
             jTextField4.setVisible(true);
             jTextField5.setVisible(true);
             jTextField6.setVisible(false);
        }
         if(jComboBox1.getSelectedItem().equals("Cuadrado")){
            jLabel2.setText("Lado");
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
             jTextField2.setVisible(false);
             jTextField3.setVisible(false);
             jTextField4.setVisible(false);
             jTextField5.setVisible(false);
             jTextField6.setVisible(false);
        }
         if(jComboBox1.getSelectedItem().equals("Rectángulo")){
            jLabel2.setText("Base");
            jLabel3.setVisible(true);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jTextField2.setVisible(true);
             jTextField3.setVisible(false);
             jTextField4.setVisible(false);
             jTextField5.setVisible(false);
             jTextField6.setVisible(false);
        }
         if(jComboBox1.getSelectedItem().equals("Rombo")){
            jLabel2.setText("Lado");
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel3.setText("D menor");
            jLabel4.setText("D mayor");
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jTextField2.setVisible(true);
             jTextField3.setVisible(true);
             jTextField4.setVisible(false);
             jTextField5.setVisible(false);
             jTextField6.setVisible(false);
        }
         if(jComboBox1.getSelectedItem().equals("Romboide")){
            jLabel2.setText("Base");
            jLabel3.setVisible(true);
            jLabel4.setVisible(false);
            jLabel3.setText("Altura");
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jTextField2.setVisible(true);
             jTextField3.setVisible(false);
             jTextField4.setVisible(false);
             jTextField5.setVisible(false);
             jTextField6.setVisible(false);
        }
         if(jComboBox1.getSelectedItem().equals("Trapecio")){
            jLabel2.setText("Lado 1");
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel3.setText("Lado 2");
            jLabel4.setText("Lado 3");
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            jLabel5.setText("Lado 4");
            jLabel6.setText("B menor");
            jLabel7.setText("B mayor");
            jTextField2.setVisible(true);
             jTextField3.setVisible(true);
             jTextField4.setVisible(true);
             jTextField5.setVisible(true);
             jTextField6.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    //variables globales
    double a=0;
    double b=0;
    double c=0;
    double d=0;
    double e=0;
    double f=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Triángulo")){
            a=Double.parseDouble(jTextField1.getText());
            b=Double.parseDouble(jTextField2.getText());
            c=Double.parseDouble(jTextField3.getText());
            d=Double.parseDouble(jTextField4.getText());
            e=Double.parseDouble(jTextField5.getText());
            JOptionPane.showMessageDialog(null, "El perímetro de la figura es "+(c+d+e)+"\n"+
                    "El área de la figura es: "+((a*b)/2));
        }
        if(jComboBox1.getSelectedItem().equals("Cuadrado")){
            a=Double.parseDouble(jTextField1.getText());
            JOptionPane.showMessageDialog(null, "El perímetro de la figura es "+(4*a)+"\n"+
                    "El área de la figura es: "+(Math.pow(a, 2)));
        }
        if(jComboBox1.getSelectedItem().equals("Rectángulo")){
            a=Double.parseDouble(jTextField1.getText());
            b=Double.parseDouble(jTextField2.getText());
            JOptionPane.showMessageDialog(null, "El perímetro de la figura es "+(2*a+2*b)+"\n"+
                    "El área de la figura es: "+(a*b));
        }
        if(jComboBox1.getSelectedItem().equals("Rombo")){
            a=Double.parseDouble(jTextField1.getText());
            b=Double.parseDouble(jTextField2.getText());
            c=Double.parseDouble(jTextField3.getText());
            JOptionPane.showMessageDialog(null, "El perímetro de la figura es "+(4*a)+"\n"+
                    "El área de la figura es: "+((b*c)/2));
        }
        if(jComboBox1.getSelectedItem().equals("Romboide")){
            a=Double.parseDouble(jTextField1.getText());
            b=Double.parseDouble(jTextField2.getText());
            JOptionPane.showMessageDialog(null, "El perímetro de la figura es "+(2*a+2*b)+"\n"+
                    "El área de la figura es: "+(a*b));
        }
        if(jComboBox1.getSelectedItem().equals("Trapecio")){
            a=Double.parseDouble(jTextField1.getText());
            b=Double.parseDouble(jTextField2.getText());
            c=Double.parseDouble(jTextField3.getText());
            d=Double.parseDouble(jTextField4.getText());
            e=Double.parseDouble(jTextField5.getText());
            f=Double.parseDouble(jTextField6.getText());
            JOptionPane.showMessageDialog(null, "El perímetro de la figura es "+(a+b+c+d)+"\n"+
                    "El área de la figura es: "+((f*(d+e))/2));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new figuras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
