/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicios.programacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class votacion extends javax.swing.JFrame {

    /**
     * Creates new form votacion
     */
    public votacion() {
        initComponents();
        setSize(452, 290);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Votación");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setText("Lista A:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setText("Lista B:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel4.setText("Lista C:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jButton1.setText("Registrar voto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jButton2.setText("Ver resultados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //variables globales
    int a=0;
    int b=0;
    int c=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            a++;
            jCheckBox1.setSelected(false);
        }
          if(jCheckBox2.isSelected()){
            b++;
            jCheckBox2.setSelected(false);
        }
            if(jCheckBox3.isSelected()){
            c++;
            jCheckBox3.setSelected(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(a>b&&a>c&&b>c){
            JOptionPane.showMessageDialog(null, "La lista ganadora es la lista A con "+a+" votos"+"\n"+"La lista B tiene "+b+" votos"+"\n"
            +"La lista C tiene "+c+" votos");
        }
        else if(a>b&&a>c&&c>b){
            JOptionPane.showMessageDialog(null, "La lista ganadora es la lista A con "+a+" votos"+"\n"+"La lista C tiene "+c+" votos"+"\n"
            +"La lista B tiene "+b+" votos");
        }
        else if(a>b&&a>c&&c==b){
            JOptionPane.showMessageDialog(null, "La lista ganadora es la lista A con "+a+" votos"+"\n"+"La lista C y la lista B tienen "+c+" votos");
        }
        else if(b>a&&b>c&&a>c){
            JOptionPane.showMessageDialog(null, "La lista ganadora es la lista B con "+b+" votos"+"\n"+"La lista A tiene "+a+" votos"+"\n"
            +"La lista C tiene "+c+" votos");
        }
         else if(b>a&&b>c&&c>a){
            JOptionPane.showMessageDialog(null, "La lista ganadora es la lista B con "+b+" votos"+"\n"+"La lista C tiene "+c+" votos"+"\n"
            +"La lista A tiene "+a+" votos");
        }
          else if(b>a&&b>c&&c==a){
            JOptionPane.showMessageDialog(null, "La lista ganadora es la lista B con "+b+" votos"+"\n"+"La lista C y la lista A tienen "+c+" votos");
        }
        else if(c>a&&c>b&&a>b){
            JOptionPane.showMessageDialog(null, "La lista ganadora es la lista C con "+c+" votos"+"\n"+"La lista A tiene "+a+" votos"+"\n"
            +"La lista B tiene "+b+" votos");
        }
         else if(c>a&&c>b&&b>a){
            JOptionPane.showMessageDialog(null, "La lista ganadora es la lista C con "+c+" votos"+"\n"+"La lista B tiene "+b+" votos"+"\n"
            +"La lista A tiene "+a+" votos");
        }
         else if(c>a&&c>b&&b>a){
            JOptionPane.showMessageDialog(null, "La lista ganadora es la lista C con "+c+" votos"+"\n"+"La lista B y la lista A tiene "+b+" votos");
        }
        else if(a==b&a>c){
            JOptionPane.showMessageDialog(null, "La lista A y B están en empate con "+a+" votos"+"\n"+
                    "La lista C tiene "+c+" votos");
        }
         else if(a==c&a>b){
            JOptionPane.showMessageDialog(null, "La lista A y C están en empate con "+a+" votos"+"\n"+
                    "La lista B tiene "+b+" votos");
        }
         else if(b==c&b>a){
            JOptionPane.showMessageDialog(null, "La lista B y C están en empate con "+b+" votos"+"\n"+
                    "La lista A tiene "+a+" votos");
        }
         else{
             JOptionPane.showMessageDialog(null, "Las tres listas estan en empate con "+a+" votos");
         }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(votacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(votacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(votacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(votacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new votacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
