/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

//import static Controladores.TLista_Dell.Guardar;

import Controladores.TLista_lenovo;
import Entidades.ExcepcionPersonalizada;
import Entidades.LaptopsLenovo;
import frmTipos.frmLenovo;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frmIngresoLenovo extends javax.swing.JFrame {

    /**
     * Creates new form frmIngresoHp
     */
    public frmIngresoLenovo() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    
    String funcion;
      public frmIngresoLenovo(String funcion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.funcion = funcion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cambio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        cambio.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        cambio.setText("Ingreso de Datos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(cambio)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cambio)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Codigo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 13, 124, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 53, 124, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("Ram:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 99, 124, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setText("Procesador:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 124, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("Tipo:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 124, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("Capacidad:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 124, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setText("Pantalla:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 124, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("Windows:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 124, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("Garantia:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 124, -1));

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 7, 252, -1));

        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 47, 252, -1));

        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 93, 252, -1));

        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 252, -1));

        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 252, -1));

        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 252, -1));

        jTextField7.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 252, -1));

        jTextField9.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 252, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setText("PrecioEfectivo:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setText("PrecioTarjeta:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 443, -1, -1));

        jTextField8.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 250, -1));

        jTextField10.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 250, -1));

        jTextField11.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 250, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, 423, 475));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/atras.png"))); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void validarDatos()throws ExcepcionPersonalizada{
        if(jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()|| jTextField6.getText().isEmpty()
        || jTextField7.getText().isEmpty()|| jTextField8.getText().isEmpty()|| jTextField9.getText().isEmpty() || jTextField10.getText().isEmpty() || jTextField11.getText().isEmpty()){
           throw new ExcepcionPersonalizada("Ha ingresado un dato incorrecto");
        }
    }
    public void establecerDatos(LaptopsLenovo estado){
        jTextField1.setText((String.valueOf(estado.getCodigo())));
        jTextField2.setText(estado.getNombreLaptop());
        jTextField3.setText(estado.getMemoriaRam());
        jTextField4.setText(estado.getProcesador());
        jTextField11.setText(estado.getTipoDisco());
        jTextField5.setText(estado.getCapacidad());
        jTextField6.setText(estado.getPantalla());
        jTextField7.setText(String.valueOf(estado.getWindows()));
        jTextField9.setText(estado.getGarantia());
        jTextField8.setText(String.valueOf(estado.getPrecioEfectivo()));
        jTextField10.setText(String.valueOf(estado.getPrecioTarjeta()));
        jTextField1.requestFocus();
    }
    
    public void obtenerDatos(){
        int codigo = Integer.valueOf(jTextField1.getText().trim());
        String nombre = jTextField2.getText().trim();
        String memoria = jTextField3.getText().trim();
        String procesador = jTextField4.getText().trim();
        String tipodisco = jTextField11.getText().trim();
        String capacidad = jTextField5.getText().trim();
        String pantalla = jTextField6.getText().trim();
        int windows = Integer.valueOf(jTextField7.getText().trim());
        String garantia = jTextField9.getText().trim();
        int precioefectivo = Integer.valueOf(jTextField8.getText().trim());
        int preciotarjeta = Integer.valueOf(jTextField10.getText());
       
        TLista_lenovo estado = new TLista_lenovo();
        if(funcion.equals("Insertar")){
            estado.insertarlaptop(new LaptopsLenovo(codigo, nombre, memoria, procesador, tipodisco, capacidad, pantalla, windows, garantia, precioefectivo, preciotarjeta));
        }else{
            estado.modificarlaptop(new LaptopsLenovo(codigo, nombre, memoria, procesador,tipodisco, capacidad,  pantalla, windows, garantia, precioefectivo, preciotarjeta));
        }
        List<LaptopsLenovo> lista = estado.listar();
        frmLenovo.jTable1.setModel(estado.mostrarTabla());
        this.dispose();
        
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        validarDatos();
        obtenerDatos();
    }catch(ExcepcionPersonalizada e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    
    }
    
//        // TODO add your handling code here:
//        if (!jTextField1.getText().equals("") && !jTextField2.getText().equals("") && !jTextField3.getText().equals("") && !jTextField4.getText().equals("") && !jTextField5.getText().equals("") &&  
//        !jTextField6.getText().equals("") && !jTextField7.getText().equals("")&& !jTextField8.getText().equals("") && !jTextField9.getText().equals("")&& jComboBox1.getSelectedIndex() > 0)
//    {
//        String Codigo = jTextField1.getText();
//        String NombreLaptop = jTextField2.getText();
//        String MemoriaRam = jTextField3.getText();
//        String Procesador = jTextField4.getText();
//        String TipoDisco = jComboBox1.getSelectedItem().toString();
//        String Capacidad = jTextField5.getText();
//        String Pantalla = jTextField6.getText();
//        int Windows = Integer.parseInt(jTextField7.getText());
//        String Garantia = jTextField9.getText();
//        double PrecioEfectivo = Double.parseDouble(jTextField8.getText());
//       
//    
////            try {
////                Guardar();
////                ListarHp();
////            } catch (IOException ex) {
////                Logger.getLogger(frmIngresoLenovo.class.getName()).log(Level.SEVERE, null, ex);
////            }
//    }
//    else
//        JOptionPane.showMessageDialog(null, "Ingrese los datos correctamente");
//        
//        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIngresoLenovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIngresoLenovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIngresoLenovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIngresoLenovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIngresoLenovo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cambio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    
}
