

package Formularios;

import Controladores.TListaAlquiler;
import Controladores.TListaEstudiantes;
import Controladores.TListaLibros;
import Entidades.Estudiante;
import Entidades.Libro;
import javax.swing.JOptionPane;
import javax.swing.JTable;


public class frmPrincipal extends javax.swing.JFrame {

    
    public frmPrincipal() {
        initComponents();
        cargardatoslibors();
        cargardatosestudiantes();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnCantidadPrestamos = new javax.swing.JButton();
        btnPorcentajePréstamos = new javax.swing.JButton();
        btnEstudiantesSancionados = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel1.setText("Biblioteca Virtual");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Insertar Libro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 120, -1));

        jButton2.setText("Modificar Libro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 120, -1));

        jButton3.setText("Eliminar Libro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 120, -1));

        jButton4.setText("Insertar Estudiante");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        jButton5.setText("Alquilar Libro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 120, -1));

        jButton6.setText("Entregar Libro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 120, -1));

        btnCantidadPrestamos.setText("Cantidad de Préstamos");
        btnCantidadPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadPrestamosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCantidadPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 160, -1));

        btnPorcentajePréstamos.setText("Porcentaje de préstamos");
        btnPorcentajePréstamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajePréstamosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPorcentajePréstamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        btnEstudiantesSancionados.setText("Estudiantes Sancionados");
        btnEstudiantesSancionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesSancionadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstudiantesSancionados, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jButton7.setText("Total libros según sexo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 690, 180));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Estudiante", "Libros" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void cargardatoslibors(){
        TListaLibros.lista.add(new Libro("001","Libro","LITERATURA","Educa","Lenguas Ecuatorianas","Gabriel Garcia","2005"));
        TListaLibros.lista.add(new Libro("002","Libro","SALUD","MSP","Como prevenir la diabetes","Dr. Albuja","2011"));
        TListaLibros.lista.add(new Libro("003","Libro","INFORMATICA","UTMACH","Estructuras de Datos","Joffre Cartuche","2009"));
        TListaLibros.lista.add(new Libro("004","Libro","EROTICO","NATURA","Mil y una noches","Mario Vargas","1999"));
        TListaLibros.lista.add(new Libro("005","Revista","LITERATURA","TEXTOS","Poemas","Pablo Neruda","2003"));
        TListaLibros.lista.add(new Libro("006","Revista","SALUD","SALUTEC","Habitos Alimenticios","Juan Piguabe","2015"));
        TListaLibros.lista.add(new Libro("007","Revista","INFORMATICA","SPACEX","Inteligencia Artificial","Elon Musk","2020"));
        TListaLibros.lista.add(new Libro("008","Revista","EROTICO","SEXTEX","La secretaria","Maria  Ojeda","2008"));
    }
    public void cargardatosestudiantes(){
        TListaEstudiantes.lista.add(new Estudiante("0987654321","Bruno","Diaz","Masculino","18/05/1999"));
        TListaEstudiantes.lista.add(new Estudiante("0123456789","Maria","quezada","Femenino","20/01/2003"));
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int index = jTable1.getSelectedRow();
        if (index>=0) {
            TListaLibros.EliminarLibro(index);
            MostrarDatos();
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un item");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmLibro f = new frmLibro();
        f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = jTable1.getSelectedRow();
        if (index>=0) {
            frmLibro f = new frmLibro(TListaLibros.get(index),index);
            f.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un item");
        }    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        frmEstudiante c = new frmEstudiante("Insertar");
        c.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frmAlquiler frm = new frmAlquiler();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String codigo = JOptionPane.showInputDialog("Ingrese el código del libro alquilado.");
        TListaAlquiler.devolverLibro(codigo);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnCantidadPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadPrestamosActionPerformed
        // TODO add your handling code here:
        TListaLibros.cantidadPrestamos();
    }//GEN-LAST:event_btnCantidadPrestamosActionPerformed

    private void btnPorcentajePréstamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajePréstamosActionPerformed
        // TODO add your handling code here:
        TListaLibros.porcentajePrestamos();
    }//GEN-LAST:event_btnPorcentajePréstamosActionPerformed

    private void btnEstudiantesSancionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesSancionadosActionPerformed
        // TODO add your handling code here:
        TListaEstudiantes.cantidadSancionados();
    }//GEN-LAST:event_btnEstudiantesSancionadosActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        TListaLibros.cantidadPrestamosLibrosPorSexo();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
        if(combo.getSelectedIndex()>0){
            jPanel1.setVisible(true);
        if(combo.getSelectedItem().equals("Libros")){
            MostrarDatos();
        }else if(combo.getSelectedItem().equals("Estudiante")){
            MostrarDatosEstudiante();
        }
        
        }
        else
           jPanel1.setVisible(false);     
                                        
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    public static void MostrarDatos(){
      jTable1.setModel(TListaLibros.MostrarDatos());
    }
    public static void MostrarDatosEstudiante(){
        jTable1.setModel(TListaEstudiantes.MostrarDatosEstudiante());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCantidadPrestamos;
    private javax.swing.JButton btnEstudiantesSancionados;
    private javax.swing.JButton btnPorcentajePréstamos;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
